# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: stalomeow/metrics@projects-v2
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: lemueldls
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_timezone: America/New_York
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          # plugin_music: yes
          # plugin_music_limit: 4
          # plugin_music_mode: top
          # plugin_music_provider: spotify
          # plugin_music_time_range: short
          # plugin_music_top_type: tracks
          # plugin_music_user: .user.login
          plugin_traffic: yes
          # plugin_wakatime: yes
          # plugin_wakatime_days: 7
          # plugin_wakatime_limit: 5
          # plugin_wakatime_repositories_visibility: all
          # plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          # plugin_wakatime_url: https://wakatime.com
          # plugin_wakatime_user: current
